/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mymlas;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ghost_000
 */
public class mgfunc extends javax.swing.JFrame {

    /**
     * Creates new form mgfunc
     */
    
    int optn;
    
    public mgfunc() throws SQLException {
        this.Management_ = new Management();
        initComponents();
        try {
            Management_ = new Management();
        }
        catch (SQLException e){
            e.printStackTrace();
        }
    }
    
    public mgfunc(int opt) throws SQLException {
        this.Management_ = new Management();
        initComponents();
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        optn = opt;
        if (optn == 1)
        {
            jPanel1.setVisible(true);
            DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();
            for(int i = 0;i < Management_.get_num_tests();i++){
                tm.addRow(new Object[] {i + 1,(Management_.list_Tests(i)).get_Testname(),(Management_.list_Tests(i)).get_Testcharges()});
            }
        }
        else if (optn==2)
        {
            jPanel2.setVisible(true);
            DefaultTableModel tm = (DefaultTableModel) jTable2.getModel();
            Connect.create_Connection(); 
            Connect.sql = "SELECT * FROM stocks;";
            ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next())
            {
                tm.addRow(new Object[]{rs.getString("Stock_Name"),0});
            }
        }
        else if (optn==3)
        {
            jPanel3.setVisible(true);
            DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
            for(int i = 0;i < Management_.get_num_tests();i++)
                tm.addRow(new Object[] {(Management_.list_Tests(i)).get_Testname()});
            for(int i = 0;i < Management_.get_num_tests();i++){
                jComboBox1.addItem((Management_.list_Tests(i)).get_Testname());
            }
        }
        else if (optn==4)
        {
            jPanel4.setVisible(true);
            DefaultTableModel tm = (DefaultTableModel) jTable4.getModel();
            Connect.create_Connection(); 
            Connect.sql = "SELECT * FROM stocks;";
            ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next())
            {
                tm.addRow(new Object[]{rs.getString("Stock_Name"),rs.getString("Quantity")});
            }
            Connect.sql = "SELECT * FROM tests;";
            rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next())
            {
                jComboBox2.addItem(""+rs.getString("Test_Name"));
            }
        }
        else if (optn==5)
        {
            jPanel5.setVisible(true);
            Connect.create_Connection();
            Connect.sql = "SELECT * FROM stocks;";
            ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next()){
                jComboBox3.addItem(rs.getString("Stock_Name"));
            }
        }
        else if (optn==6)
        {
            jPanel6.setVisible(true);
            DefaultTableModel tm = (DefaultTableModel) jTable5.getModel();
            tm.setRowCount(0);
            Connect.create_Connection();
            Connect.sql = "SELECT * FROM orders WHERE Status = 'Pending';";
            ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next()){
                tm.addRow(new Object[] {rs.getString("Stock_Name"),rs.getInt("Quantity")});
                jComboBox4.addItem(rs.getString("Stock_Name"));
            }
        }
        else if (optn==7)
        {
            jPanel7.setVisible(true);
        }
        else if (optn==8)
        {
            jPanel8.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton13 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 960, 200);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("List of Tests");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 180, 960, 40);

        jButton1.setText("Go Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 510, 180, 25);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial No.", "Test Name", "Charges"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 940, 270);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(0, 0, 960, 200);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 51, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Add Test");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 180, 960, 40);

        jButton2.setText("Go Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(400, 510, 180, 25);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel13.setText("Test Name");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(40, 250, 110, 30);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel14.setText("Charges");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(490, 250, 130, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(160, 250, 250, 30);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(640, 250, 290, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Stocks Required");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 300, 890, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(40, 340, 890, 130);

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7);
        jButton7.setBounds(400, 480, 180, 25);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 960, 200);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 51, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Remove Test");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 180, 960, 40);

        jButton3.setText("Go Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(400, 510, 180, 25);

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Available Tests");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 240, 440, 23);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Name"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(20, 280, 440, 220);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Select Test to Remove");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(510, 240, 440, 23);

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1);
        jComboBox1.setBounds(510, 280, 430, 40);

        jButton8.setText("Confirm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);
        jButton8.setBounds(640, 360, 180, 25);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel4.add(jLabel7);
        jLabel7.setBounds(0, 0, 960, 200);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 51, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Edit Test");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 180, 960, 40);

        jButton4.setText("Go Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(400, 510, 180, 25);

        jButton9.setText("Update");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);
        jButton9.setBounds(400, 480, 180, 25);

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel18.setText("Select Test");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(40, 250, 110, 30);

        jLabel19.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel19.setText("Charges");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(490, 250, 130, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField4);
        jTextField4.setBounds(640, 250, 290, 30);

        jLabel20.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Stocks Required");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(40, 300, 890, 30);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(40, 340, 890, 130);

        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(170, 250, 270, 30);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(960, 540));
        jPanel5.setMinimumSize(new java.awt.Dimension(960, 540));
        jPanel5.setLayout(null);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel5.add(jLabel9);
        jLabel9.setBounds(0, 0, 960, 200);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 51, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Place Order");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(0, 180, 960, 40);

        jButton5.setText("Go Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(400, 510, 180, 25);

        jLabel25.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel25.setText("Select Stock");
        jPanel5.add(jLabel25);
        jLabel25.setBounds(40, 250, 160, 30);

        jPanel5.add(jComboBox3);
        jComboBox3.setBounds(230, 250, 270, 30);

        jLabel26.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("Quantity");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(40, 300, 160, 30);

        jTextField3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel5.add(jTextField3);
        jTextField3.setBounds(230, 300, 270, 30);

        jButton12.setText("Order");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);
        jButton12.setBounds(400, 480, 180, 25);

        jPanel9.setOpaque(false);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 960, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel9);
        jPanel9.setBounds(0, 0, 960, 540);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(null);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel6.add(jLabel11);
        jLabel11.setBounds(0, 0, 960, 200);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 51, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Change Order Status");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(0, 180, 960, 40);

        jButton6.setText("Go Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(400, 510, 180, 25);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stock Ordered", "Quantity"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel6.add(jScrollPane5);
        jScrollPane5.setBounds(20, 280, 440, 210);

        jLabel27.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Current Orders");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(20, 240, 440, 23);

        jLabel28.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Modify Order Status for");
        jPanel6.add(jLabel28);
        jLabel28.setBounds(510, 240, 440, 23);

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox4);
        jComboBox4.setBounds(510, 280, 430, 40);

        jRadioButton1.setText("Recieved");
        jPanel6.add(jRadioButton1);
        jRadioButton1.setBounds(510, 340, 200, 25);

        jRadioButton2.setText("Cancel");
        jPanel6.add(jRadioButton2);
        jRadioButton2.setBounds(737, 340, 200, 25);

        jButton13.setText("Confirm");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton13);
        jButton13.setBounds(630, 390, 190, 25);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(null);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel7.add(jLabel21);
        jLabel21.setBounds(0, 0, 960, 200);

        jLabel22.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 51, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Modify Order");
        jPanel7.add(jLabel22);
        jLabel22.setBounds(0, 180, 960, 40);

        jButton10.setText("Go Back");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);
        jButton10.setBounds(400, 510, 180, 25);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mymlas/marie.png"))); // NOI18N
        jPanel8.add(jLabel23);
        jLabel23.setBounds(0, 0, 960, 200);

        jLabel24.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 51, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("New Stock Item");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(0, 180, 960, 40);

        jButton11.setText("Go Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11);
        jButton11.setBounds(400, 510, 180, 25);

        jLabel29.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel29.setText("Stock Name");
        jPanel8.add(jLabel29);
        jLabel29.setBounds(40, 250, 160, 30);

        jLabel30.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Threshold");
        jPanel8.add(jLabel30);
        jLabel30.setBounds(40, 350, 160, 30);

        jLabel31.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("Quantity");
        jPanel8.add(jLabel31);
        jLabel31.setBounds(40, 300, 160, 30);

        jTextField5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel8.add(jTextField5);
        jTextField5.setBounds(230, 250, 270, 30);

        jTextField6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel8.add(jTextField6);
        jTextField6.setBounds(230, 300, 270, 30);

        jTextField7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel8.add(jTextField7);
        jTextField7.setBounds(230, 350, 270, 30);

        jButton14.setText("Order");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14);
        jButton14.setBounds(400, 480, 180, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Management_home mghm = new Management_home(1);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Management_home mghm = new Management_home(1);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Management_home mghm = new Management_home(1);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            Management_home mghm = new Management_home(1);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            Management_home mghm = new Management_home(2);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            Management_home mghm = new Management_home(2);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            Management_home mghm = new Management_home(2);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            Management_home mghm = new Management_home(2);
            mghm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            String indx = jComboBox1.getSelectedItem().toString();
            Test_to_remove = indx;
            try {
                Management_.remove_Test(Test_to_remove);
            }
            catch (SQLException e) {
                e.printStackTrace();
            }
            DefaultTableModel tm = (DefaultTableModel) jTable3.getModel();
            tm.setRowCount(0);
            Connect.create_Connection();
            Connect.sql = "SELECT * FROM tests;";
            ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
            while(rs.next())
            {
                tm.addRow(new Object[]{rs.getString("Test_Name")});
            }
            jComboBox1.removeAllItems();
            for(int i = 0;i < Management_.get_num_tests();i++)
                jComboBox1.addItem((Management_.list_Tests(i)).get_Testname());
        }
        catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if(jTextField4.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Enter all the details and then press Update.\n");
        }
        else if(!jTextField4.getText().matches("[0-9]*")){
            JOptionPane.showMessageDialog(null, "Charges can contain only numbers(0 to 9)!");
        }
        else {
            String S = "";
            DefaultTableModel dtm = (DefaultTableModel) jTable4.getModel();
            int nRow = dtm.getRowCount();
            for (int i = 0 ; i < nRow ; i++)
            {
                S=S.concat(dtm.getValueAt(i, 1).toString());
            }
            Test prev_test = Management_.list_Tests(jComboBox2.getSelectedIndex());
            Test new_test  = new Test(prev_test.get_Testname(),Integer.parseInt(jTextField4.getText()),S);
            try {
                if(Management_.edit_Test(prev_test, new_test)){
                    jTextField4.setText("");
                    jComboBox2.removeAllItems();
                    //EditTest.dispose();
                    JOptionPane.showMessageDialog(null,"The Test has been successfully edited.\n");
                }
                else {
                    JOptionPane.showMessageDialog(null,"Sorry this test matches with a test already added.\nEnter the new test again.\n");
                }
            }
            catch (SQLException e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if(jTextField1.getText().equals("") || jTextField2.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Enter all the fields and then press Done.\n");
            }
            else if(jTextField2.getText().matches("[0-9]*")){
                System.out.println("OUT!");
                try {
                    System.out.println("IN!!!!!!!!");
                    String S = "";
                    DefaultTableModel dtm = (DefaultTableModel) jTable2.getModel();
                    int nRow = dtm.getRowCount();
                    for (int i = 0 ; i < nRow ; i++)
                    {
                        System.out.println(dtm.getValueAt(i,1).toString());
                        S=S.concat(dtm.getValueAt(i, 1).toString());
                        S=S.concat(",");
                    }
                    S=S.concat("-");
                    Test test_temp = new Test(jTextField1.getText(),Integer.parseInt(jTextField2.getText()),S);  
                    if(Management_.add_Test(test_temp)){
                        JOptionPane.showMessageDialog(null,"The test has been successfully added!!");
                    }
                    else {
                        JOptionPane.showMessageDialog(null,"Sorry the test already exists!!");
                    }
                jTextField1.setText("");
                jTextField2.setText("");
                //AddTest.dispose();
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Test Charges can only consist of numbers.");
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {                                          
            Stocks S = new Stocks(jComboBox3.getSelectedItem().toString(),Integer.parseInt(jTextField3.getText()),0);
            Connect.create_Connection();
            Connect.sql = "INSERT INTO orders (Stock_Name,Quantity,Status,Threshold) VALUES ('"+ jComboBox3.getSelectedItem().toString() +"',"+ jTextField3.getText() +",'Pending',-1);";
            Connect.stmt.executeUpdate(Connect.sql);
            JOptionPane.showMessageDialog(null,"Done.\n");
            Connect.stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

      public int deleteStocks(Stocks s) throws SQLException
    {
        
        //////////////////////////
//        returns
//                0 : insufficient stocks;
//                1 : successful;
//                2 : no such stocks;
       //////////////////////////
        
        Connect.create_Connection();
        Connect.sql = "SELECT * FROM Stocks WHERE Stock_Name = '" + s.get_Item_Name() + "';";
        ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
        int quantity = 0;
        boolean flag = false,flag2 = false;
        while(rs.next()){
            flag2 = true;
            quantity = rs.getInt("Quantity");
//            if(quantity + s.get_Quantity() >= rs.getInt("Threshold")){
//                flag = true;
//            }
            quantity = quantity - s.get_Quantity();
            if(quantity < 0)
                return 0;
        }
//        if(flag == true) {
//            Connect.sql = "DELETE FROM NotifyStocks WHERE Item_Name = '" + item.get_Item_Name() + "';";
//            Connect.stmt.executeUpdate(Connect.sql);
//        }
        //else 
        if(flag2 == true) {
             Connect.sql = "UPDATE Stocks SET Quantity = " + quantity + " WHERE Item_Name = '" + s.get_Item_Name() + "';";
             Connect.stmt.executeUpdate(Connect.sql);
             JOptionPane.showMessageDialog(null,"Done.\n");
             return 1;
        }
//        Connect.sql = "SELECT * FROM Stocks WHERE Item_Name = '" + s.get_Item_Name() + "';";
//        rs = Connect.stmt.executeQuery(Connect.sql);
//        while(rs.next()){
//            quantity = rs.getInt("Quantity") + s.get_Quantity();
//        }
//        Connect.sql = "UPDATE Stocks SET Quantity = " + quantity + " WHERE Item_Name = '" + item.get_Item_Name() + "';";
//        Connect.stmt.executeUpdate(Connect.sql);
        
        return 2;
    }
    
    public void addStocks(Stocks s) throws SQLException
    {
         Connect.create_Connection();
        Connect.sql = "SELECT * FROM orders WHERE Stock_Name = '" + s.get_Item_Name() + "' AND Status = 'Pending';";
        ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
        int srno = 0;
        while(rs.next())
        {
            srno = rs.getInt("id");
        }
        Connect.sql = "UPDATE orders SET Status = 'Received' WHERE id = " + srno + " AND Status <> 'Received';";
        Connect.stmt.executeUpdate(Connect.sql);
        Connect.sql = "SELECT * FROM stocks WHERE Stock_Name = '" + s.get_Item_Name() + "';";
        System.out.println(s.get_Item_Name());
        rs = Connect.stmt.executeQuery(Connect.sql);
        int quantity = 0, y = 0;
        boolean flag = false,flag2 = false;
        while(rs.next()){
            flag2 = true;
            quantity = rs.getInt("Quantity");
            y = quantity;
            quantity = quantity + s.get_Quantity();
            //System.out.println(quantity);
        }
        
        if(flag2 == true) {
             Connect.sql = "UPDATE stocks SET Quantity = " + quantity + " WHERE Stock_Name = '" + s.get_Item_Name() + "';";
             Connect.stmt.executeUpdate(Connect.sql);
             //Connect.sql = "DELETE FROM stocks WHERE Stock_Name = '" + s.get_Item_Name() + "' AND Quantity = " + y + ";";
             JOptionPane.showMessageDialog(null,"Stocks added.\n");
        }  
    }
    
    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
         Stocks S = null;
        int f=0;
        if (jRadioButton1.isSelected())
        {
            try {
                Connect.create_Connection();
                Connect.sql = "SELECT * FROM orders WHERE Stock_Name='"+ jComboBox4.getSelectedItem().toString() + "' AND Status = 'Pending';";
                ResultSet rs = null;
                rs = Connect.stmt.executeQuery(Connect.sql);
                rs.next();
                f=1;
                S = new Stocks();
                S.set_Item_Name(rs.getString("Stock_Name"));
                S.set_Quantity(rs.getInt("Quantity"));
                S.set_Threshold(rs.getInt("Threshold"));
            } catch (SQLException ex) {
                Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (f==1){
                if (S.get_Threshold()>0)
                {
                    try {
                        //System.out.println("1");
                        newStocks(S);
                    } catch (SQLException ex) {
                        Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
                       }
                }
                else
                {
                    try {
                        //System.out.println("2");
                        addStocks(S);
                    } catch (SQLException ex) {
                        Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
                       }
                }
            }
        }
        
        if (jRadioButton2.isSelected())
        {
            try {
                Connect.create_Connection();
                Connect.sql = "SELECT * FROM orders WHERE Stock_Name='"+ jComboBox4.getSelectedItem().toString() + "';";
                ResultSet rs = null;
                rs = Connect.stmt.executeQuery(Connect.sql);
                rs.next();
                f=1;
                S = new Stocks();
                S.set_Item_Name(rs.getString("Stock_Name"));
                S.set_Quantity(rs.getInt("Quantity"));
                S.set_Threshold(rs.getInt("Threshold"));
            } catch (SQLException ex) {
                Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
            }
            if (f==1){
                try {
                    Connect.create_Connection();
                    Connect.sql = "SELECT * FROM orders WHERE Stock_Name = '" + S.get_Item_Name() + "' AND Status = 'Pending';"; 
                    ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
                    int srno = 0;
                    while(rs.next())
                    {
                        srno = rs.getInt("id");
                    }
                    Connect.sql = "UPDATE orders SET Status = 'Cancelled' WHERE id = " + srno + ";";
                    Connect.stmt.executeUpdate(Connect.sql);
                    JOptionPane.showMessageDialog(null,"Order cancelled.\n");
                } catch (SQLException ex) {
                    Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    public void newStocks(Stocks s) throws SQLException
    {
        Connect.create_Connection();
        Connect.sql = "SELECT * FROM orders WHERE Stock_Name = '" + s.get_Item_Name() + "' AND Status = 'Pending';";
        ResultSet rs = Connect.stmt.executeQuery(Connect.sql);
        int srno = 0;
        while(rs.next())
        {
            srno = rs.getInt("id");
        }
        Connect.sql = "UPDATE orders SET Status = 'Received' WHERE id = " + srno + " AND Status <> 'Received';";
        Connect.stmt.executeUpdate(Connect.sql);
        
        Connect.sql = "INSERT INTO stocks (Stock_Name,Quantity,Threshold) VALUES ('"+ s.get_Item_Name() + "'," + s.get_Quantity() + ","+ s.get_Threshold() + ");";
        Connect.stmt.executeUpdate(Connect.sql);
         
        JOptionPane.showMessageDialog(null,"Stocks added.\n");
    }
    
    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            Stocks S;
            Connect.create_Connection();
            Connect.sql = "INSERT INTO orders (Stock_Name,Quantity,Status,Threshold) VALUES ('"+ jTextField5.getText() +"',"+ jTextField6.getText() +",'Pending',"+ jTextField7.getText() +");";
            Connect.stmt.executeUpdate(Connect.sql);
            JOptionPane.showMessageDialog(null,"Done.\n");
            Connect.stmt.close();
        } catch (SQLException ex) {
            Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mgfunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mgfunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mgfunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mgfunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new mgfunc().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(mgfunc.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public Management Management_;
    public String Test_to_remove;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
